CREATE TABLE `TL_USERS` (
  `SEQ` int(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '일련번호',
  `USER_ID` varchar(255) NOT NULL DEFAULT '' COMMENT '사용자 ID',
  `USER_NAME` varchar(255) NOT NULL DEFAULT '',
  `PASSWORD` varchar(255) NOT NULL,
  `FRST_ISRT_DT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '최초입력일시',
  `LAST_PROC_DT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP() COMMENT '최종처리일시',
  PRIMARY KEY (`SEQ`),
  UNIQUE KEY `UK_TL_USERS_USER_ID` (`USER_ID`)
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci;
